services:
  - type: web
    name: spendwise
    runtime: java
    plan: free
    buildCommand: ./build.sh
    startCommand: java -Dserver.port=$PORT -jar target/SpendWise.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: spendwise-db
    databaseName: spendwise
    user: spendwise
    plan: free
