services:
  - type: web
    name: spendwise
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
      - key: DATABASE_URL
        fromDatabase:
          name: spendwise-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: spendwise-db
    databaseName: spendwise
    user: spendwise
    plan: free
