services:
  - type: web
    name: spendwise
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: spendwise-db
    databaseName: spendwise
    user: spendwise
    plan: free
